### ISSUE TITLE
Add property "record_level_file_version_declaration" to work models

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/britishlibrary#330]
# Story

In order to fulfill Plan S requirements, a new property is needed on work types which may be peer-reviewed. Add `record_level_file_version_declaration` question & checkbox to models Article, Conference Item, and Generic Work. 

The client suggested that this checkbox be added to the files tab if possible.

# Acceptance Criteria

- [ ] Models Article, Conference Item and Generic Work have new question & checkbox added
- [ ] Value can be added both in UI and via Bulkrax import
- [ ] Value is optional, and works save with or without it checked
- [ ] Value can be edited and re-saved from the files tab when editing a work

CSV file for import should have column `file_declaration` with a value of `1` on the work to set the flag.
 [Sample CSV file](https://github.com/scientist-softserv/britishlibrary/files/11066894/Archive.zip)

# Testing Instructions

- [ ] Add works through the UI. Verify that the file tab shows the question & checkbox on the appropriate work types and not for other work types.
- [ ] Edit works through the UI. Verify that the file tab is pre-checked for works where it was previously set.
- [ ] Add works through Bulkrax using provided file. Edit work in the UI and verify that the file tab is pre-checked.
  - [ ]  [Sample CSV file](https://github.com/scientist-softserv/britishlibrary/files/11066894/Archive.zip)

# Notes
Ref https://github.com/scientist-softserv/britishlibrary/issues/104
[Plan S technical guidance document](https://www.coalition-s.org/technical-guidance_and_requirements/)

**Comment by ShanaLMoore** [comment]
Does the client have a recommendation for the predicate uri to use?

**Comment by laritakr** [comment]
@jeremyf was looking for the URI to use, I believe...

**Comment by laritakr** [comment]
After discussion, decided to go with property `UsageAndAccessPolicy` as long as there are no duplicate predicate errors

https://github.com/ruby-rdf/rdf-vocab/blob/a6d073b6ac647645b7d9f5a6bd7f8688bb7378f6/lib/rdf/vocab/bf2.rb#L1075-L1079

**Comment by laritakr** [comment]
Referencing the `Acceptance Criteria` and sample file from the ticket description:
- [ ] Add works through the UI. Verify that the file tab shows the question & checkbox on the appropriate work types and not for other work types.
- [ ] Edit works through the UI. Verify that the file tab is pre-checked for works where it was previously set.
- [ ] Add works through Bulkrax using provided file. Edit work in the UI and verify that the file tab is pre-checked.

**Comment by DiemBTran** [comment]
**Needs further review:**

tested on:
- `new work form` > `files` tab: https://bl.bl-staging.notch8.cloud/concern/articles/new?locale=en#files
- conference item that should not be checked: https://bl.bl-staging.notch8.cloud/concern/conference_items/ba066f29-853e-46b3-8c0d-ceb98b4fa3e5/edit?locale=en#files
- busted Bulkrax importer: https://bl.bl-staging.notch8.cloud/importers/56?locale=en

Passes:
- [x] Add works through the UI. Verify that the file tab shows the question & checkbox on the appropriate work types and not for other work types. [link to screenshot with checkbox](https://share.getcloudapp.com/o0uYRy1A) [link to screenshot without checkbox](https://share.getcloudapp.com/yAuJKP0W)


Doesn't pass:

- [ ] Edit works through the UI. Verify that the file tab is pre-checked for works where it was previously set.
  - For works that were created with the box checked, this data persists. The edit form shows that the box is checked. 
  - For works that were made without the box checked, this data does not persist. The edit form shows that the box is checked, even though it wasn't checked during creation. [link to screen recording](https://share.getcloudapp.com/Z4un7egz)

Blocked:
- [ ] Add works through Bulkrax using provided file. Edit work in the UI and verify that the file tab is pre-checked.
  - I cannot test this because we're waiting for the Bulkrax .zip fix [link to screenshot](https://share.getcloudapp.com/jkuAv7e0)

**Comment by ShanaLMoore** [comment]
# QA RESULTS:

**Comment by ShanaLMoore** [comment]
Graham noticed that the exported value was simply an "f" instead of the full name "file declaration": 

ref slack convo: https://assaydepot.slack.com/archives/C0313NK2LJ0/p1683124610866229

To resolve this, we needed to update the bulkrax field mapping to be an array. I will push this change to staging and ping Graham, soon.

**Comment by ShanaLMoore** [comment]
cc @grahamjevon The fix the the exporter is available on staging now.

exporter: https://bl.bl-staging.notch8.cloud/exporters/34?locale=en
exported file: 
[export_34_49_1.zip](https://github.com/scientist-softserv/britishlibrary/files/11390724/export_34_49_1.zip)

**Comment by ShanaLMoore** [comment]
@grahamjevon We are going to make two separate tickets for your bullet points. 

We will create one to considering handling boolean values instead. 

Additionally, the declaration only applies to the CSV parser currently. We would need to know what xml node the ETD parser should map to, in order to set up xml. ref: https://github.com/scientist-softserv/britishlibrary/blob/main/config/initializers/bulkrax.rb#L189

**Comment by jillpe** [comment]
Noting that the additional 2 tickets created are added scope and are not part of AHRC

**Comment by jillpe** [comment]
@ShanaLMoore yes this should be worked on
