### ISSUE TITLE
Signed out user access to child works

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/britishlibrary#404]
# Story

LaRita discovered a strange bug. 

When a user is logged out, they are unable to click on the child works. When doing so, the child works tries to download instead of redirecting the user to the child's show page. This results in a 400 error. 

# Acceptance Criteria

- [ ] When clicking on a child work in the items section, a user should be able to view a child work's show page (if they have access to do so when logged out). If not, fail gracefully (with an error message or something).
- [ ] When clicking on a file set in the items section, a user should get the download action

# Screenshots / Video

As a logged out user, ref: https://bl.bl-staging.notch8.cloud/concern/books/68c2aa73-7947-488c-bc96-695ac4b04f3f?locale=en

When clicking on a child work: 
<img width="1350" alt="image" src="https://user-images.githubusercontent.com/10081604/236900058-122b7b1b-dc76-4820-becd-093e6a5476d5.png">

# Testing Instructions and Sample Files

- Log out of the application. 
- Find a work that has child works
- Click on a child work, it should redirect you to the child show page if the user has access to view it. 
  - it should not lead you to an error page 

# Notes

What is the expected behavior for when a logged out user clicks on a file set?

**Comment by kirkkwang** [comment]
This was related to an issue I did as an intern.  I found the gitlab issue
https://gitlab.com/notch8/britishlibrary/-/issues/254

Here's the commit
https://github.com/scientist-softserv/britishlibrary/commit/a4c27cb9a31d6ab88a2b7721a34122064c194159

To replicate it, this is what it said

# Summary

On the work metadata page list of files, most users click the filename expecting it to download but it goes to the View file page - poor ux and nothing useful for users on that page. Ditto the thumbnail.
The main download button on the work metadata page is hidden behind 'Actions' dropdown.
Depositor email address is displayed to users on View file page - needs to be hidden.
If a user lands on View file page from outside the repository there is no way to find their way to the work metadata page - cannot find out title, author of the work or details to cite it - poor ux.

# Requirements

Remove all public access to the View File page.  In the work metadata page, make the filenames listed in the list of files produce an immediate download.  In the work metadata page, make the thumbnails in list of files also produce an immediate download.  Leave the actions dropdown as is now.  

# Acceptance Criteria
- [x] On Items, thumbnails are a download link
- [x] On items, titles are a download link
- currently we are leaving the File View so that machines can still mine the data.  

# Screen shot
![image](https://user-images.githubusercontent.com/19597776/236962064-4911ad96-ce94-4cd7-91e5-afd3a88b36f8.png)

**Comment by ShanaLMoore** [comment]
@DeonFranklin associated PR: https://gitlab.com/notch8/britishlibrary/-/merge_requests/353/diffs

If you need to login, us Rob's credentials in one password

<img width="788" alt="image" src="https://github.com/scientist-softserv/britishlibrary/assets/10081604/be02c808-2955-424a-8a13-91c44d8a8f2b">

**Comment by jeremyf** [comment]
Wondering if shifting from the following:

```erb
  <td class="attribute attribute-filename ensure-wrapped">
    <% if user_signed_in? %>
      <%= link_to(member.link_name, contextual_path(member, @presenter)) %>
    <% else %>
      <%= link_to(member.link_name, hyrax.download_path(member.id), target: :_blank) %>
    <% end %>
  </td>
```

to this:

```erb
  <td class="attribute attribute-filename ensure-wrapped">
    <%= link_to(member.link_name, contextual_path(member, @presenter)) %>
  </td>
```

Would that be a generally acceptable change?

https://github.com/scientist-softserv/britishlibrary/blob/4f385229ce9cf7ad8b081b677d9a589ce0651f6d/app/views/hyrax/base/_member.html.erb#L11-L17

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- parent work: https://bl.bl-staging.notch8.cloud/concern/books/f2118ba5-6712-46ab-9e1f-6244c2542a0f?locale=en
- child work: https://bl.bl-staging.notch8.cloud/concern/parent/f2118ba5-6712-46ab-9e1f-6244c2542a0f/books/4c8767ca-f4b8-4013-aa07-23ce0a14d7e8

<details><summary>Clicking a child work successfully leads to its work show page without error</summary>

https://github.com/scientist-softserv/britishlibrary/assets/29311858/5e9968c2-75f2-444f-9012-8b7b5aa69913
</details>
