### ISSUE TITLE
🎁 UV Download option - question mark

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/britishlibrary#430]
# Summary
ref:

- #313  

Should this "?" be replaced with something more definite?

![Image](https://github.com/scientist-softserv/britishlibrary/assets/84697174/88cc4b4e-6297-4724-b05e-1f7377ba39ed)

# Acceptance Criteria
- [ ] The question mark is replaced with the image type

**Comment by jillpe** [comment]
related to #429

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://mola.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://mola.bl-staging.notch8.cloud/concern/articles/3a3e4542-ec27-4748-93ea-3fad5a0c3b05/manifest&config=https://mola.bl-staging.notch8.cloud/uv/uv-config.json

<details><summary>The download option now says "(jpg)" instead of "?"</summary>

![mola bl-staging notch8 clouduvuv html#manifest=mola bl-staging notch8 cloudconcernarticles3a3e4542-ec27-4748-93ea-3fad5a0c3b05manifest config=mola bl-staging notch8 clouduvuv-config json 2023-05-26 at 1 21 04 PM (1)](https://github.com/scientist-softserv/britishlibrary/assets/29311858/dc42f4b0-c10d-4c2c-84b5-2b54b1529614)
</details>

**Comment by grahamjevon** [comment]
This does not pass BL QA. I added [a work with a jpeg on staging](https://bl.bl-staging.notch8.cloud/concern/books/707033f9-2e2d-42ae-9155-70c5c205242c?locale=en) and I can still see the ? in the download option.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/51366817/ec828daa-57b5-4e34-ac79-559f5111eaef)

**Comment by kirkkwang** [comment]
@grahamjevon again i'm seeing something different than you are

<img width="1728" alt="image" src="https://github.com/scientist-softserv/britishlibrary/assets/19597776/3137c5f5-6a26-4d4c-bffd-8376d8822e8f">
