### ISSUE TITLE
Work giving: sorry something went wrong

### ISSUE THREAD

**Issue by j-basford** [scientist-softserv/britishlibrary#455]
Trying to access this show work page: https://bl.iro.bl.uk/concern/datasets/117ed6c1-d9ba-481a-bae6-74d389f6a441 

Gives the error 'sorry something went wrong' 

Accessed 17:58 BST 10/7/23 if you need to check logs.

It also has a DOI that points to it: https://doi.org/10.23636/1176
Metadata to look up the item: 'Text extracted from digitised maps of eastern Africa circa 1880-1940' by Nick Dykes, added 2020-05-22.

It is in this collection: https://bl.iro.bl.uk/collections/2edd9ec0-b5fe-42d8-9844-3373256da0d1 (War Office Archive)

**Comment by cziaarm** [comment]
recording this here...

ActionView::Template::Error (undefined method `id' for nil:NilClass):
--
Mon, Jul 10 2023 6:57:40 pm | F, [2023-07-10T17:57:40.277636 #1] FATAL -- : [b706a2a4e122f17defcef67b56e70df7] 1: <%# OVERRIDE Hyrax 2.9.1 and 2 parts from the main branch as of 7/14/2021 . There was a bug for 2.9.1-2.9.5 that caused the feature/unfeature buttons to show up on the work-show page for editors when they should not. This has since been fixed but this override retroactively changes the issue. %>
Mon, Jul 10 2023 6:57:40 pm | [b706a2a4e122f17defcef67b56e70df7] 2:
Mon, Jul 10 2023 6:57:40 pm | [b706a2a4e122f17defcef67b56e70df7] 3: <div class="show-actions">
Mon, Jul 10 2023 6:57:40 pm | [b706a2a4e122f17defcef67b56e70df7] 4: <% if presenter.iiif_viewer? %>
Mon, Jul 10 2023 6:57:40 pm | [b706a2a4e122f17defcef67b56e70df7] 5: <%= link_to 'View files in viewer',
Mon, Jul 10 2023 6:57:40 pm | [b706a2a4e122f17defcef67b56e70df7] 6: "#{universal_viewer_base_url}#?manifest=#{main_app.polymorphic_url [main_app, :manifest, presenter], { locale: nil }}&config=#{universal_viewer_config_url}",
Mon, Jul 10 2023 6:57:40 pm | [b706a2a4e122f17defcef67b56e70df7] 7: class: 'btn btn-default devise-button',
Mon, Jul 10 2023 6:57:40 pm | F, [2023-07-10T17:57:40.277669 #1] FATAL -- : [b706a2a4e122f17defcef67b56e70df7]
Mon, Jul 10 2023 6:57:40 pm | F, [2023-07-10T17:57:40.277706 #1] FATAL -- : [b706a2a4e122f17defcef67b56e70df7] app/presenters/concerns/hyrax/iiif_av/displays_iiif_av_decorator.rb:14:in `file_type_and_permissions_valid?'


https://scientist-inc.sentry.io/issues/4293978732/?query=is%3Aunresolved+undefined+method&referrer=issue-stream&sort=betterPriority&statsPeriod=14d&stream_index=0

**Comment by cziaarm** [comment]
I think this is being tickled by a representative media, that has since been removed... The work does not appear to have any files currently... is it possible that it did once? Specifically one called War_Office_Archive_Eastern_Africa_Text_Harvested__2_.xlsx

**Comment by cziaarm** [comment]
Rightio... 

So that original file (a0e081fc-3d1e-49de-b2a4-8be2d8c973d7 to its friends) was always there but as you say there must have been something gone awry with the indexing. I have reindexed the original fileset and hey presto: https://bl.iro.bl.uk/concern/datasets/117ed6c1-d9ba-481a-bae6-74d389f6a441 back in the room, but with both files. I will leave it to your discretion to choose which to keep.

Thanks
