### ISSUE TITLE
Only one author appears in works with multiple authors.

### ISSUE THREAD

**Issue by NoraRamsey** [scientist-softserv/britishlibrary#476]
Working on the Kew tenant, I noticed some works which should have multiple authors listed only have one.
Example: [https://kew.iro.bl.uk/concern/articles/cec71cca-30c1-4926-898c-892fd2f3c4e2](https://kew.iro.bl.uk/concern/articles/cec71cca-30c1-4926-898c-892fd2f3c4e2)

In the main search it will appear correctly 

![Image](https://github.com/scientist-softserv/britishlibrary/assets/124701578/88384e33-d371-4b85-abc0-c49f86343a13)

But in the record only one author will appear, and the rest will be only blank space.

![Image](https://github.com/scientist-softserv/britishlibrary/assets/124701578/8b30ba1b-e42b-4852-be98-b00eea989041)

![Image](https://github.com/scientist-softserv/britishlibrary/assets/124701578/2e9d8422-c138-48b6-85ab-035434209269)

I've come across this issue mostly with while searching for records with Stevenson, P. C. as the author, but it may be found elsewhere as well.

**Comment by cziaarm** [comment]
Hi @NoraRamsey,

 the reason these creators are not appearing is because they did not have the "Creator Name Type" sub-field set.

Setting these values will mean the creators appear in the view: https://kew.iro.bl.uk/concern/articles/cec71cca-30c1-4926-898c-892fd2f3c4e2?locale=en (I did this one)

How did they end up this way? (The creator names should default to "Personal")

This is example has been around since 2021 so one possibility is that they are left over from migration or a previous, another is that these records were imported using incomplete metadata.

I'll move this over to client verification so you can confirm what I've said makes sense / is true

**Comment by NoraRamsey** [comment]
Thanks for this Rory! This makes sense. Happy that there's an easy fix for this.
